---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.02.2020 20:49

function DeeperShip()
	local ThisTrigger = CreateTrigger()
	TriggerRegisterEnterRectSimple(ThisTrigger, gg_rct_DeapZone1)
	TriggerAddAction(ThisTrigger, function()
		print("Создаём перевернутые корабли")
		DisableTrigger(GetTriggeringTrigger())
		local x,y
		for i=1, 5 do
			x,y=GetRandomReal(GetRectMinX(gg_rct_DeapZone1), GetRectMaxX(gg_rct_DeapZone1)), GetRandomReal(GetRectMinY(gg_rct_DeapZone1), GetRectMaxY(gg_rct_DeapZone1))
			local new=CreateUnit(Player(11), FourCC('u001'), x, y, 0)
			MakeShipDeep(new)
		end

	end)
end


function MakeShipDeep(hero)
	SetUnitAnimation(hero,"Death")
	SetUnitTimeScale(hero,10)
	TimerStart(CreateTimer(), 3/10, false, function()
		SetUnitTimeScale(hero,0)

		TimerStart(CreateTimer(), 3.7, false, function()

			StartSheepAIDeepAggressor(hero)
		end)
	end)
end

function StartSheepAIDeepAggressor(hero)
	if UnitAI[GetHandleId(hero)]==nil then
		--	print("Запущен первый прототип ИИ")
	else
		print("ОШИБКА, НЕВОЗМОЖНО ИЗМЕНИТЬ ТИП ИИ")
	end
	UnitAI[GetHandleId(hero)]={
		IsMove=true,
		IsAttack=false,
		--IsEscape=false,
		RandomTimeFactor=GetRandomReal(-.5,0)
	}
	local data=UnitAI[GetHandleId(hero)]
	TimerStart(CreateTimer(), ReactionAI+data.RandomTimeFactor, true, function()--поиск врага 1 секунда по умлочанию
		local e=nil
		local x,y=GetUnitXY(hero)
		local enemy=nil
		GroupEnumUnitsInRange(perebor,x,y,600,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(hero))  then--and IsUnitVisible(e,GetOwningPlayer(hero))
				enemy=e

				if data.IsAttack==false then
					SetUnitTimeScale(hero,-0.5)
					SetUnitAnimation(hero,"Death")
				end
				data.IsAttack=true
				--print("Найден враг "..GetUnitName())
			end
			GroupRemoveUnit(perebor,e)
		end
		if enemy~=nil then
			--local xe,ye=GetUnitXY(enemy)
			--IssuePointOrder(hero,"move",xe,ye)
			IssueTargetOrder(hero,"move",enemy)
			SingleCannon(hero)
		end
		if UnitAlive(hero)==false then
			DestroyTimer(GetExpiredTimer())
			SetUnitTimeScale(hero,1)
			SetUnitAnimation(hero,"Death")
			--	print("умираю....")
		end
	end)
end