---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.03.2020 1:03
function BossZoneInit()
	local ThisTrigger = CreateTrigger()
	TriggerRegisterEnterRectSimple(ThisTrigger, gg_rct_AAAAAAAA)
	TriggerAddAction(ThisTrigger, function()
		print("Запускаем ИИ босса")
		local boss=nil -- определение босса
		DisableTrigger(GetTriggeringTrigger())
		--Закрываем ворота
		StartTentacleBossAI(boss)
	end)
end

function BossZoneInit(hero)
	local faze=0
	TimerStart(CreateTimer(), 5, false, function()
		faze=faze+1
		print("Фаза "..faze)
		if faze==1 then

		elseif faze==2 then

		elseif faze==3 then

		elseif faze==4 then
			faze=0
			print("Сброс фаз "..faze)
		end


	end)
end