---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.02.2020 18:42
---
function InitZone1()
	TimerStart(CreateTimer(), 10, true, function()
		--CreateZombies()
		InitZombies()
	end)
end



function InitZombies()--ужасно, больше так не буду делать, мозголомание бредовое
	local e=nil
	local k=0
	local id=FourCC('n003')
	if OrcSkeletonPool[4]<=OrcSkeletonPool[5]*3 then
		GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and GetUnitTypeId(e)==id then
				local r=GetRandomInt(1,3)
				k=k+1
				if OrcSkeletonPool[5+k]==nil then
					OrcSkeletonPool[5+k]=e
				end

				if OrcSkeletonPool[4]<OrcSkeletonPool[5]*3 then
					if GetUnitUserData(e)<3 then
						local orc=CreateUnit(GetOwningPlayer(e), OrcSkeletonPool[r],GetUnitX(e),GetUnitY(e),0)
						OrcSkeletonPool[4]=OrcSkeletonPool[4]+1
						GroupAddUnit(OrcSkeletonPoolG,orc)
						SetUnitUserData(orc,GetHandleId(e))
						SetUnitUserData(e,GetUnitUserData(e)+1)
						--print("создан скелет"..GetUnitUserData(e))
					end
				else

				end



			end
			GroupRemoveUnit(perebor,e)
		end
		--print("Запущено пил: "..k)
		OrcSkeletonPool[5]=k
	end
end

OrcSkeletonPoolG=CreateGroup()
OrcSkeletonPool={
	FourCC('n000'),
	FourCC('n001'),
	FourCC('n002'),
	0,--число скелетов
	4,--число обелисков
	nil,
	nil,
	nil,
	nil,
}