---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.02.2020 18:42
---
function InitZone1()
	TimerStart(CreateTimer(), 10, true, function()
		--CreateZombies()
		InitZombies()
		--gg_rct_TestFog

	end)
	--print("0")
	CreateFogInRect(gg_rct_TestFog)
end

function CreateFogInRect(rect)
	--print("1")
	local xMax,yMax=GetRectMaxX(rect),GetRectMaxY(rect)
	local xMin,yMin=GetRectMinX(rect),GetRectMinY(rect)
	local step=70
	local Wide=R2I(math.abs(xMax-xMin)/step)
	local Height=R2I(math.abs(yMax-yMin)/step)
	local xPos,yPos=xMax,yMax
	local fog={}
	print("x="..Wide.." y="..Height)
	for i=0,Wide do
		xPos=MoveX(xMax,-step*i,0)
		--print("Создан туман по х="..i)
		for k=0,Height do
			yPos=MoveY(yMax,-step*k,90)
			--fog[i]=
			--print("Создан туман по y="..k)
			local eff =AddSpecialEffect("smoke",xPos,yPos) --WaterOrb --bluegas
			SetEffectAlphaNearHero(eff)
		end
	end
end

function SetEffectAlphaNearHero(eff)
	local x,y=BlzGetLocalSpecialEffectX(eff),BlzGetLocalSpecialEffectY(eff)
	TimerStart(CreateTimer(), 0.3, true, function()
		if PointContentUnit(x,y,450) then
			BlzSetSpecialEffectAlpha(eff,100)
			--print("alpha")
			BlzPlaySpecialEffect(eff,ANIM_TYPE_DEATH)
			DestroyEffect(eff)
			DestroyTimer(GetExpiredTimer())
			--BlzSetSpecialEffectTime(eff,2300)
			BlzSetSpecialEffectPosition(eff,4000,4000,0)
		else
			BlzSetSpecialEffectAlpha(eff,0)
			BlzPlaySpecialEffect(eff,ANIM_TYPE_STAND)
			BlzSetSpecialEffectPosition(eff,x,y,0)
		end
	end)
end




function InitZombies()--ужасно, больше так не буду делать, мозголомание бредовое
	local e=nil
	local k=0
	local id=FourCC('n003')
	if OrcSkeletonPool[4]<=OrcSkeletonPool[5]*3 then
		GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and GetUnitTypeId(e)==id then
				local r=GetRandomInt(1,3)
				k=k+1
				if OrcSkeletonPool[5+k]==nil then
					OrcSkeletonPool[5+k]=e
				end

				if OrcSkeletonPool[4]<OrcSkeletonPool[5]*3 then
					if GetUnitUserData(e)<3 then
						local orc=CreateUnit(GetOwningPlayer(e), OrcSkeletonPool[r],GetUnitX(e),GetUnitY(e),0)
						OrcSkeletonPool[4]=OrcSkeletonPool[4]+1
						GroupAddUnit(OrcSkeletonPoolG,orc)
						SetUnitUserData(orc,GetHandleId(e))
						SetUnitUserData(e,GetUnitUserData(e)+1)
						--print("создан скелет"..GetUnitUserData(e))
					end
				else

				end



			end
			GroupRemoveUnit(perebor,e)
		end
		--print("Запущено пил: "..k)
		OrcSkeletonPool[5]=k
	end
end

OrcSkeletonPoolG=CreateGroup()
OrcSkeletonPool={
	FourCC('n000'),
	FourCC('n001'),
	FourCC('n002'),
	0,--число скелетов
	4,--число обелисков
	nil,
	nil,
	nil,
	nil,
}