---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.02.2020 20:49

function InMineWay()
	local gg_trg_InMineWay = CreateTrigger()
	TriggerRegisterEnterRectSimple(gg_trg_InMineWay, gg_rct_Zone03In)
	TriggerAddAction(gg_trg_InMineWay, function()

	end)
end