---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.01.2020 23:44
---
---
---@param data table
---@param str string
---@return string
function string.gsuber(data, str)
	for k, v in pairs(data) do
		str = string.gsub(str, '[' .. k .. ']', v)
	end
	return str
end

do
	local GetAbilityDescriptionOriginalTable = {} ---@type table

	function GetAbilityDescriptionOriginal(id)
		--print("0.6")
		if GetAbilityDescriptionOriginalTable[id] == nil then
			GetAbilityDescriptionOriginalTable[id] = BlzGetAbilityExtendedTooltip(id,0)
		--	print("0.7")
		end
		return GetAbilityDescriptionOriginalTable[id]
	end
	function UnitRefreshAbilityTooltip(caster,id)
		local NativeString=GetAbilityDescriptionOriginal(id)
		local data=HERO[GetHandleId(caster)]
		local player=GetOwningPlayer(caster)

		if id==data.TalantW.AbilID then -- описание способности
			print("условие выполнено")
			if data.TalantW.AddChain then
				--NativeString = string.gsuber({ mrange = 1400 }, NativeString)
			else
				--NativeString = string.gsuber({ mrange = 700 }, NativeString)
				NativeString =string.gsub(NativeString,"mrange","700")
			end
			print("Результат NativeString="..NativeString)
			BlzSetAbilityExtendedTooltip(id,NativeString,0)
			BlzSetAbilityExtendedTooltip(id,NativeString,1)
		end
		--print("Проверка "..NativeString)
	end
end

---
function InitTalantItemUse()
	gg_trg_TalantItemUse = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_TalantItemUse, EVENT_PLAYER_UNIT_PICKUP_ITEM)
	TriggerAddAction(gg_trg_TalantItemUse, function()
		local item=GetManipulatedItem()
		local hero=GetTriggerUnit()
		local data=HERO[GetHandleId(hero)]
		--таланты способности W

		if GetItemTypeId(item)==FourCC('I000') then --дополнительные звенья
			data.TalantW.AddChain=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --Мясной крюк
			data.TalantW.MeatHook=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --Ядро
			data.TalantW.AddCore=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --фиксатор
			data.TalantWFixed=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --корчеватель пней
			data.TalantW.Willow=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --наковальня
			data.TalantW.Unwil=true
		elseif GetItemTypeId(item)==FourCC('I00X') then --пудж
			data.TalantW.Pudge=true
		end
	end)
end