---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.02.2020 21:08
ReactionAI=1
UnitAI={}

function StartSheepAI(hero)

	if UnitAI[GetHandleId(hero)]==nil then
	--	print("Запущен первый прототип ИИ")
	else
		print("ОШИБКА, НЕВОЗМОЖНО ИЗМЕНИТЬ ТИП ИИ")
	end
	UnitAI[GetHandleId(hero)]={
		IsMove=true,
		IsAttack=false,
		IsEscape=false,
		RandomTimeFactor=GetRandomReal(-.5,.5)
	}
	local data=UnitAI[GetHandleId(hero)]

	TimerStart(CreateTimer(), ReactionAI+data.RandomTimeFactor, true, function()--поиск врага 1 секунда по умлочанию
		local e=nil
		local x,y=GetUnitXY(hero)
		local enemy=nil
		GroupEnumUnitsInRange(perebor,x,y,1000,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(hero)) and IsUnitVisible(hero,GetOwningPlayer(e)) and data.IsEscape==false then
				enemy=e
				data.IsAttack=true
				--print("Найден враг "..GetUnitName())
			end
			GroupRemoveUnit(perebor,e)
		end
		if enemy~=nil then
			local xe,ye=GetUnitXY(enemy)
			if IsUnitInRange(hero,enemy,100) then
				if data.IsEscape==false then
					local escapeX,escapeY=MoveXY(xe,ye,1000,GetUnitFacing(hero)-180)
					--print("Слишком близко!")
					data.IsEscape=true
					data.IsAttack=false
					IssuePointOrder(hero,"move",escapeX,escapeY)
					TimerStart(CreateTimer(), 3, false, function()--3 секунды отсутпления
						DestroyTimer(GetExpiredTimer())
						data.IsEscape=false
						data.IsAttack=true
						--print("снова в бой")
					end)
				end
			else
				if data.IsEscape==false then
					if GetUnitCurrentOrder(hero)~=String2OrderIdBJ("move") then
						IssuePointOrder(hero,"move",xe,ye)
					end
					SingleCannon(hero)
				end
			end
		end
		if UnitAlive(hero)==false then
			DestroyTimer(GetExpiredTimer())
		--	print("умираю....")
		end
	end)
end