---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05

---Глобалки
TIMER_PERIOD = 0.03125
HERO={}
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		InitGameCore()
		hideEverything()
		InitMouseMoveTrigger()
	end

end

function InitGameCore()
	--создаём героев
	--BlzEnableSelections(false,false)
	EnableDragSelect(false,false)
	HERO[0]={
		ReleaseW=false,
		ReleaseS=false,
		ReleaseA=false,
		ReleaseD=false,
		Acceleration=0,
		ReleaseLMB=false,
		ReleaseRMB=false,
		SpeedBase=14,
		UnitHero=CreateUnit(Player(0), FourCC('H000'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0),
		CurrentSpeed=0,
		WeaponIndex=1,
		AngleForce=0, --типа какой-то уго для отталкивания
		IsDisabled=false
	}
	BlzLoadTOCFile("Main.toc")
	BlzLoadTOCFile("MySimpleButton.toc")
	BlzLoadTOCFile("BoxedText.toc")
	local HealthPlayer1 = HealthBarAdd(HERO[0].UnitHero)
	BlzFrameSetAbsPoint(HealthPlayer1, FRAMEPOINT_TOPRIGHT, 0.8, 0.57)
	SelectUnitForPlayerSingle(HERO[0].UnitHero,GetOwningPlayer(HERO[0].UnitHero))

	--CreateWeaponFrame()
	CreateWeaponFrame()



--триггеры
	-----------------------------------------------------------------OSKEY_1
	local TrigWeaponSwitch1 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch1,Player(i),OSKEY_1,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch1, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=1
		--print("press1")
	end)
	-----------------------------------------------------------------OSKEY_2
	local TrigWeaponSwitch2 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch2,Player(i),OSKEY_2,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch2, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=2
		--print("press2")
	end)
	-----------------------------------------------------------------OSKEY_3
	local TrigWeaponSwitch3 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch3,Player(i),OSKEY_3,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch3, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=3
		--print("press3")
	end)
	-----------------------------------------------------------------OSKEY_4
	local TrigWeaponSwitch4 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch4,Player(i),OSKEY_4,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch4, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=4
		--print("press1")
	end)
	-----------------------------------------------------------------OSKEY_5
	local TrigWeaponSwitch5 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch5,Player(i),OSKEY_5,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch5, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=5
		--print("press1")
	end)
	-----------------------------------------------------------------OSKEY_6
	local TrigWeaponSwitch6 = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigWeaponSwitch6,Player(i),OSKEY_6,0,true)
	end
	TriggerAddAction(TrigWeaponSwitch6, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.WeaponIndex=6
		--print("press1")
	end)
	-----------------------------------------------------------------OSKEY_W
	local gg_trg_EventUpW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpW,Player(i),OSKEY_W,0,true)
	end
	TriggerAddAction(gg_trg_EventUpW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=true
	end)
	local TrigDepressW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDepressW,Player(i),OSKEY_W,0,false)
	end
	TriggerAddAction(TrigDepressW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=false
	end)
	-----------------------------------------------------------------OSKEY_D
	local TrigPressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressD,Player(i),OSKEY_D,0,true)
	end
	TriggerAddAction(TrigPressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		--BlzStartUnitAbilityCooldown(data.UnitHero,FourCC('A002'),5)
		data.ReleaseD=true
	end)
	local TrigDePressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressD,Player(i),OSKEY_D,0,false)
	end
	TriggerAddAction(TrigDePressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseD=false
	end)
	-----------------------------------------------------------------OSKEY_A
	local TrigPressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressA,Player(i),OSKEY_A,0,true)
	end
	TriggerAddAction(TrigPressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=true
	end)
	local TrigDePressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressA,Player(i),OSKEY_A,0,false)
	end
	TriggerAddAction(TrigDePressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=false
	end)
	-----------------------------------------------------------------LMB
	local TrigPressLMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigPressLMB, Player(0), EVENT_PLAYER_MOUSE_DOWN)
	TriggerAddAction(TrigPressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=true
			local hero=data.UnitHero
			if data.WeaponIndex==2 then
				BoardCannon(hero,90,GetRandomInt(5,5))
			end
			if data.WeaponIndex==4 then
				CreateFire(hero,90)
			end
		end
	end)
	local TrigDePressLMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigDePressLMB, Player(0), EVENT_PLAYER_MOUSE_UP)
	TriggerAddAction(TrigDePressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=false
		end
	end)
	-----------------------------------------------------------------RMB
	local TrigPressRMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigPressRMB, Player(0), EVENT_PLAYER_MOUSE_DOWN)
	TriggerAddAction(TrigPressRMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseRMB=true
			local hero=data.UnitHero
			if data.WeaponIndex==1 then
				SingleCannon(hero)
			end
			if data.WeaponIndex==2 then
				BoardCannon(hero,-90,GetRandomInt(5,5))
			end
			if data.WeaponIndex==4 then
				CreateFire(hero,-90)
			end
			if data.WeaponIndex==3 then
				UnitRocketArea(hero,GetPlayerMouseX[pid],GetPlayerMouseY[pid],200)
			end

		end
	end)
	local TrigDePressRMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigDePressRMB, Player(0), EVENT_PLAYER_MOUSE_UP)
	TriggerAddAction(TrigDePressRMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseRMB=false
		end
	end)

	-----------------------------------------------------------------Lock
	TimerStart(CreateTimer(), 0.01, true, function()
		local data=HERO[0]
		local hero=data.UnitHero
		ForceUIKeyBJ(GetOwningPlayer(hero),"M")
		IssueImmediateOrder(hero,"stop")
	end)

	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		for _, data in pairs(HERO) do
			local hero= data.UnitHero
			local camerax,cameray=MoveX(GetUnitX(hero),data.CurrentSpeed*20,GetUnitFacing(hero)),MoveY(GetUnitY(hero),data.CurrentSpeed*20,GetUnitFacing(hero))
			--SetCameraPositionForPlayer(GetOwningPlayer(hero),camerax,cameray)
			PanCameraToTimedForPlayer(GetOwningPlayer(hero),camerax,cameray,1)
			UnitCheckPathingInRound(hero,90)

			if data.ReleaseLMB then
			--if data.WeaponIndex==
				--data.ReleaseA=false
				--data.ReleaseD=false
				--data.ReleaseW=false
				--print("Error LMB")
			end

			if data.ReleaseW then
				if data.Acceleration<=data.SpeedBase then
					data.Acceleration=data.Acceleration+1
				end
			else
				if data.Acceleration>0 then
					data.Acceleration=data.Acceleration-1
				end
			end
			if data.ReleaseD then
				BlzSetUnitFacingEx(hero,GetUnitFacing(hero)-5)
				--SetUnitFacing(hero,GetUnitFacing(hero)-10)
			end
			if data.ReleaseA then
				BlzSetUnitFacingEx(hero,GetUnitFacing(hero)+5)
				--SetUnitFacing(hero,GetUnitFacing(hero)+10)
			end

			data.CurrentSpeed=data.Acceleration
			if data.CurrentSpeed>0 then--попытка сделать разгон
					--print("текущая скорость = "..data.CurrentSpeed)
				local x,y=GetUnitX(hero),GetUnitY(hero)
				local angle=GetUnitFacing(hero)
				data.AngleForce=angle
				local zhero=GetTerrainZ(x,y)
				if zhero<=-90 then
					--SetUnitZ(hero,-89.9)
					--print("провалился в яму")
				end
				local newX3,newY3=MoveX(x,180,angle),MoveY(y,180,angle)
				local newX2,newY2=MoveX(x,120,angle),MoveY(y,120,angle)
				local z3=GetTerrainZ(newX3,newY3)
				local z2=GetTerrainZ(newX2,newY2)
				--print("z="..z)
				if z3<=-80 and z2<=-80 and PointContentUnit(newX2,newY2,100)==false then
					--print("проходима")
					local newX,newY=MoveX(x,data.CurrentSpeed,angle),MoveY(y,data.CurrentSpeed,angle)
					SetUnitX(hero,newX)
					SetUnitY(hero,newY)
				else
					--print("не проходима")
					--BlzSetUnitFacingEx(hero,angle-15)
					IssueImmediateOrder(hero,"stop")
					--angle=angle-180
				end


			end
		end
	end)
end

function UnitCheckPathingInRound(hero,range)
	local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
	local x,y=GetUnitX(hero),GetUnitY(hero)
	local nx,ny=nil,nil
	local a=10
	local z=nil
	local k=0
	local total=0
	local med=0
	local min=350
	local max=0
	local current=0
	local dif=0
	for i=0,35 do
		nx=MoveX(x,range,a*i)
		ny=MoveY(y,range,a*i)
		z=GetTerrainZ(nx,ny)
		if z>-80 then--or PointContentUnit(nx,ny,60) then
			k=k+1
			total=total+a*i
			current=a*i
			if current>=max then max=current end
			if current<=min then min=current end
			--print("a="..a*i)
			DestroyEffect(AddSpecialEffect("Abilities/Weapons/AncestralGuardianMissile/AncestralGuardianMissile.mdl",nx,ny))
		end
	end
	if k>0 then
		dif=max-min
		if dif>=90 then
			--print("dif="..dif.."при минимуме="..min)
			for i=min,0,-10 do
				total=total+360
			end
		end

		med=total/k

		--print("Средний угол"..med)
		--local newmed=AngleDifferenceDeg(min,max)
		if data.IsDisabled==false then
			--print("Число точек "..k)
			--print("med="..med)--.." newmed="..newmed)
			--print ("min="..min.." max="..max)
			--print("Угол юнита"..GetUnitFacing(hero))
			if k>=7 then
				--print("selfdamage")
				UnitDamageTarget( hero, hero, 10*(k-7), true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
			end
			data.IsDisabled=true
			if dif>=90 then med=med-180 end
			UnitAddForce(hero,med-180,5,80)
		end
	end



end
function UnitAddForce(hero,angle,speed,distance)
	local currentdistance=0
	local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		currentdistance=currentdistance+speed
		local x,y=GetUnitX(hero),GetUnitY(hero)
		local newX,newY=MoveX(x,speed,angle),MoveY(y,speed,angle)
		SetUnitX(hero,newX)
		SetUnitY(hero,newY)
		if currentdistance>=distance then
			data.IsDisabled=false
			DestroyTimer(GetExpiredTimer())
			--print("stop")
		end
	end)
end

function PointContentUnit(x,y,range)
	local content=false
	local e--временный юнит
	GroupEnumUnitsInRange(perebor,x,y,range,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if UnitAlive(e)  then
			--UnitDamageTarget( u, e, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
			content=true
		end
		GroupRemoveUnit(perebor,e)
	end
	return content
end


