---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05

---Глобалки
TIMER_PERIOD = 0.03125
HERO={}
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		InitGameCore()
	end

end

function InitGameCore()
	--создаём героев
	--BlzEnableSelections(false,false)
	EnableDragSelect(false,false)
	HERO[0]={
		ReleaseW=false,
		ReleaseS=false,
		ReleaseA=false,
		ReleaseD=false,
		Acceleration=0,
		ReleaseLMB=false,
		SpeedBase=14,
		UnitHero=CreateUnit(Player(0), FourCC('H000'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0),
		CurrentSpeed=0
	}
--триггеры
	-----------------------------------------------------------------OSKEY_W
	local gg_trg_EventUpW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpW,Player(i),OSKEY_W,0,true)
	end
	TriggerAddAction(gg_trg_EventUpW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=true
	end)
	local TrigDepressW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDepressW,Player(i),OSKEY_W,0,false)
	end
	TriggerAddAction(TrigDepressW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=false
	end)
	-----------------------------------------------------------------OSKEY_D
	local TrigPressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressD,Player(i),OSKEY_D,0,true)
	end
	TriggerAddAction(TrigPressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		--BlzStartUnitAbilityCooldown(data.UnitHero,FourCC('A002'),5)
		data.ReleaseD=true
	end)
	local TrigDePressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressD,Player(i),OSKEY_D,0,false)
	end
	TriggerAddAction(TrigDePressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseD=false
	end)
	-----------------------------------------------------------------OSKEY_A
	local TrigPressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressA,Player(i),OSKEY_A,0,true)
	end
	TriggerAddAction(TrigPressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=true
	end)
	local TrigDePressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressA,Player(i),OSKEY_A,0,false)
	end
	TriggerAddAction(TrigDePressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=false
	end)
	-----------------------------------------------------------------LMB
	local TrigPressLMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigPressLMB, Player(0), EVENT_PLAYER_MOUSE_DOWN)
	TriggerAddAction(TrigPressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=true
		end
	end)
	local TrigDePressLMB=CreateTrigger()
	TriggerRegisterPlayerEvent(TrigDePressLMB, Player(0), EVENT_PLAYER_MOUSE_UP)
	TriggerAddAction(TrigDePressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=false
		end
	end)

	-----------------------------------------------------------------
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		for _, data in pairs(HERO) do
			local hero= data.UnitHero
			--etCameraPositionForPlayer(GetOwningPlayer(hero),GetUnitX(hero),GetUnitY(hero))
			PanCameraToTimedForPlayer(GetOwningPlayer(hero),GetUnitX(hero),GetUnitY(hero),0.3)
			if data.ReleaseLMB then
				data.ReleaseA=false
				data.ReleaseD=false
				data.ReleaseW=false
				print("Error LMB")
			end

			if data.ReleaseW then
				if data.Acceleration<=data.SpeedBase then
					data.Acceleration=data.Acceleration+1
				end
			else
				if data.Acceleration>0 then
					data.Acceleration=data.Acceleration-1
				end
			end
			if data.ReleaseD then
				BlzSetUnitFacingEx(hero,GetUnitFacing(hero)-5)
				--SetUnitFacing(hero,GetUnitFacing(hero)-10)
			end
			if data.ReleaseA then
				BlzSetUnitFacingEx(hero,GetUnitFacing(hero)+5)
				--SetUnitFacing(hero,GetUnitFacing(hero)+10)
			end

			data.CurrentSpeed=data.Acceleration
			if data.CurrentSpeed>0 then--попытка сделать разгон
					--print("текущая скорость = "..data.CurrentSpeed)

				SetUnitX(hero,MoveX(GetUnitX(hero),data.CurrentSpeed,GetUnitFacing(hero)))
				SetUnitY(hero,MoveY(GetUnitY(hero),data.CurrentSpeed,GetUnitFacing(hero)))
			end
		end
	end)
end
