---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.01.2020 23:10
---
do
	function InitDamage()
		local DamageTrigger = CreateTrigger()
		for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
			TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
			TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
		end
		TriggerAddAction(DamageTrigger, function()
			local damage     = GetEventDamage() -- число урона
			local damageType = BlzGetEventDamageType()
			if damage < 1 then return end
			
			local eventId         = GetHandleId(GetTriggerEventId())
			local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
			local isEventDamaged  = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)
			
			local target          = GetTriggerUnit() -- тот кто получил урон
			local targetHandleId  = GetHandleId(target)
			local caster          = GetEventDamageSource() -- тот кто нанёс урон
			local casterOwner     = GetOwningPlayer(caster)
			
			if isEventDamaged then
				-- ReactiveArmor
				local data = HERO[targetHandleId]
				if damageType == DAMAGE_TYPE_NORMAL and data ~= nil then
					local charges        = data.ReactiveArmorChargesTime
					----TODO добавить снятие лимита
					if data.FirstDamage==false then
						--print("FirstDamage")
						data.FirstDamage=true
						AddUnitToStock(target, ReactiveArmorUnit, 0, 0)
						QuestMessageBJ(GetPlayersAllies(GetOwningPlayer(target)), bj_QUESTMESSAGE_UNITAVAILABLE, "|cffffff00Апргейд:|r Доступна новая способность - Реактивная броня")
					end
					local chargeMinIndex = 1 -- индекс заряда с минимальным значением
					for i = 2, #charges do
						if charges[i] < charges[chargeMinIndex] then
							chargeMinIndex = i
						end
					end
					charges[chargeMinIndex] = SECOND + ReactiveArmorCooldown
					
					local chargeCount       = 0 -- количество активных зарядов
					for i = 1, #charges do
						if charges[i] > SECOND then
							chargeCount = chargeCount + 1
							--UNIT_RF_HIT_POINTS_REGENERATION_RATE
						end
					end

					UnitSetBonus(target,5,chargeCount)--армор
					UnitSetBonus(target,6,chargeCount)--hpregen
					if chargeCount>=#charges then
						--print("получен урон при максимальных зарядах")
					end
					AddUnitToStock(data.unit, ReactiveArmorUnit, chargeCount, chargeCount)
				end
			end
		end)
	end
end