---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.01.2020 1:15
---
-----
DestructableState={}
function InitDestructablesActions()
	AnyDeathDestructEnum = CreateTrigger()
	--AnyDeathDestruct = CreateTrigger()
	EnumDestructablesInRect(bj_mapInitialPlayableArea,nil, function()
		TriggerRegisterDeathEvent(AnyDeathDestructEnum, GetEnumDestructable())
	end)
	TriggerAddAction(AnyDeathDestructEnum, function()
		local d=GetTriggerDestructable()
		--print("умер"..GetDestructableName(d))
		local SpawnTime=GetRandomInt(30,60)
		if DestructableState[GetHandleId(d)]==nil then
			local xd, yd = GetDestructableX(d), GetDestructableY(d)
			local unit, dist
			for handle, data in pairs(HERO) do
				local hero   = data.unit
				local dx, dy = GetUnitX(hero) - xd, GetUnitY(hero) - yd
				local d      = dx * dx + dy * dy
				if unit == nil then
					unit = hero
					dist = d
				elseif d < dist then
					unit = hero
					dist = d
				end
			end
			AddLumber(1,unit)
		end
		DestructableState[GetHandleId(d)]=nil
		TimerStart(CreateTimer(), SpawnTime, false, function()
			DestructableRestoreLife(d, GetDestructableMaxLife(d), true)
			PauseTimer(GetExpiredTimer())
			DestroyTimer(GetExpiredTimer())
		end)
	end)
end

GlobalRect=Rect(0,0,0,0)
function KillTreeInRange (x,y,range)
	local k=0
	SetRect(GlobalRect, x - range, y - range, x + range, y +range)
	EnumDestructablesInRect(GlobalRect,nil,function ()
		local d=GetEnumDestructable()
		if GetDestructableLife(d)>0 and (GetDestructableTypeId(d)==(FourCC('ATtc')) or GetDestructableTypeId(d)==(FourCC('ATtr'))  or GetDestructableTypeId(d)==(FourCC('FTtw'))
		or GetDestructableTypeId(d)==(FourCC('B001'))) then --
			k=k+1
			DestructableState[GetHandleId(d)]=1-- параметр означает, что дерево уничтожено способностью
			--print("найдено дерево")
			KillDestructable(d)
		end
	end)
	return k
end
function AddLumber (ttk,caster)
	local ownplayer=GetOwningPlayer(caster)
	if ttk>0 then
		FlyTextTagLumberBounty(caster,"+"..ttk,ownplayer)
		AdjustPlayerStateBJ(ttk, ownplayer, PLAYER_STATE_RESOURCE_LUMBER )
		local data=HERO[GetHandleId(caster)]
		data.TreeCount=data.TreeCount+ttk
		if data.TreeCount>10 and data.TreeCount<20  then
			UnitAddAbility(caster,FourCC('A001'))
		end
	end
end