---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
---
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		-- заменяем оригинальную InitGlobals своей
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		--добавляем в список функции для инициализации
		InitSpellTrigger()
		InitMouseMoveTrigger()
		--print("globalinit")
		InitGameCore()
		InitDamage()
		InitTimers()
		InitDestructablesActions()
		InitUnitDeath()
		InitTalants()
		InitTalantItemUse()
		--InitShop()
	end

end
HERO                  = {} -- таблица героев
HERO_ID               = FourCC('H000') -- ид единственного героя
ReactiveArmorCooldown = 10 -- время снятия заряда пассивки
ReactiveArmorUnit     = FourCC('n000')
HEROSimple            = {} -- упрощённая таблица
Quest                 = {} -- таблица квестов
Talants               = {} -- таблица юнитов талантов

function InitGameCore()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		if i==0 then -- GetPlayerController(player) == MAP_CONTROL_USER and GetPlayerSlotState(player) == PLAYER_SLOT_STATE_PLAYING then

			--FIXME сделать нормальное появление героя
			local hero = CreateUnit(player, HERO_ID, -7042, 6910, 0)
			local WaitReturner = CreateUnit(player, FourCC('e001'), -0, 0, 0)--юнит требование, для возврата пилы
			local pid=GetPlayerId(player)
			--базовые знания героев
			UnitAddAbility(hero, FourCC('Asud')) -- Продажа юнита
			UnitAddAbility(hero,FourCC('A003'))--возврат пилы
			BlzUnitHideAbility(hero,FourCC('A003') ,true)-- и скрыть

			--таблицы
			Talants[pid]={
				main=CreateUnit(player, FourCC('e005'), -0, 0, 0),
				q=CreateUnit(player, FourCC('e006'), -0, 0, 0),
				w=CreateUnit(player, FourCC('e004'), -0, 0, 0),
				e=CreateUnit(player, FourCC('e007'), -0, 0, 0),
				r=CreateUnit(player, FourCC('e008'), -0, 0, 0)

			}
			TimerStart(CreateTimer(), 1, true, function()
				local data=Talants[pid]
				local x,y=GetUnitX(hero),GetUnitY(hero)
				SetUnitPosition(data.main,x,y)
				SetUnitPosition(data.q,x,y)
				SetUnitPosition(data.w,x,y)
				SetUnitPosition(data.e,x,y)
				SetUnitPosition(data.r,x,y)
			end)
			---------------------------------------------------------------
			HEROSimple[pid]=hero
			HERO[GetHandleId(hero)] = {--стартовые параметры героя
				unit                 = hero, -- ссылка на юнита
				ReactiveArmorChargesTime = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, -- время снятия заряда, количество зарядов определяется количество элементов
				ReactiveArmorLimit   = true, -- ограниченное количество зарядов
				WaitReturnerUnit = WaitReturner,
				ChakrumUnit=nil,
				IsReturned=false,
				FirstDamage=false,
				KillCount=0,
				TreeCount=0,
				TalantQ={

				},
				TalantW={
					AbilID=FourCC('A001'),
					AddChain=false,
					MeatHook=false,
					AddCore=false,
					Fixed=false,
					Willow=false,
					Unwil=false,
					Pudge=false
				}
			}
			QuestRegistrator(hero)-- Событие приближения к квестовым объектам

		end--цикл всех игроков
	end
	--инициализация квестов
	local questmax=20
	for i = 1, questmax do
		--print("добавление квестов")
		Quest[i]={
			isend=false,
			questendunit=nil,
			hero=nil,
			isactive=false
		}
	end

end



