---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.01.2020 22:52
---
SECOND = 0
function InitTimers()
	TimerStart(CreateTimer(), 1, true, function()
		SECOND = SECOND + 1
		
		-- ReactiveArmor
		for _, data in pairs(HERO) do
			local hero         = data.unit
			local charges      = data.ReactiveArmorChargesTime
			local chargesCount = 0
			if data.FirstDamage then
				-- считаем количество активных зарядов
				for i = 1, #charges do
					if charges[i] >= SECOND then
						chargesCount = chargesCount + 1
					end
				end
				UnitSetBonus(hero,5,chargesCount)--армор
				UnitSetBonus(hero,6,chargesCount)--Hpregen
				AddUnitToStock(hero, ReactiveArmorUnit, chargesCount, chargesCount)
			end
		end
	end)
end
