---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 06.02.2020 18:00
---
---
---
---
--BlzLoadTOCFile("Main.toc")
--HealthPlayer1 = HealthBarAdd(udg_Pala)
--BlzFrameSetAbsPoint(HealthPlayer1, FRAMEPOINT_TOPRIGHT, 0.8, 0.57)

function HealthBarAdd(u)
	print("Creating \'"..GetHeroProperName(u).."\' Bar")

	--создаём фрейм по имени
	local bar = BlzCreateSimpleFrame("MyFakeBar", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0)

	--делаем видимым
	BlzFrameSetVisible(bar,true)

	--ставим текстурки
	BlzFrameSetTexture(bar, "Replaceabletextures\\Teamcolor\\Teamcolor00.blp", 0, true)
	BlzFrameSetTexture(BlzGetFrameByName("MyFakeBarBorder",0),"MyBarBorder.blp", 0, true)

	--текст по центру
	BlzFrameSetText(BlzGetFrameByName("MyFakeBarTitle",0), GetHeroProperName(u))

	--сейвим фреймы текста справа и слева для автообновления
	local lefttext = BlzGetFrameByName("MyFakeBarLeftText",0)
	local righttext = BlzGetFrameByName("MyFakeBarRightText",0)

	--функция обновления
	local function on_timer()
		--ставим бар
		BlzFrameSetValue(bar, GetUnitLifePercent(u))

		--обновляем текст слева и справа
		BlzFrameSetText(lefttext, R2I(GetWidgetLife(u)))
		BlzFrameSetText(righttext, R2I(BlzGetUnitMaxHP(u)))
	end

	--стартуем функцию обновления
	TimerStart(CreateTimer(),0.5,true, on_timer)

	--ретурним сам бар для дальнейших действий
	return bar
end